SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Bootstrap",
    "React",
    "Next.js",
    "Django",
    "Flask",
    "FastAPI",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "OpenCV",
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Scikit-learn",
    "MySQL",
    "SQLite",
    "Chart.js",
    "SQLAlchemy",
    "MongoDB",
    "PostgreSQL",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "REST API",
    "REST APIs",
    "Machine Learning",
    "Deep Learning",
    "NLP"
]