"""Global knowledge base for skill-gap learning guidance."""

from __future__ import annotations

SKILL_GUIDE: dict[str, dict[str, str]] = {
    "Python": {
        "reason": "Python is a widely used language for backend development, automation, and data science workflows.",
        "learning_path": "Python Basics → Functions → OOP → Libraries → Projects",
        "estimated_time": "2 Weeks",
        "priority": "High",
    },
    "Java": {
        "reason": "Java is commonly used for enterprise services, backend systems, and Android development.",
        "learning_path": "Java Basics → OOP → Collections → Concurrency → Spring Boot",
        "estimated_time": "2 Weeks",
        "priority": "High",
    },
    "C": {
        "reason": "C remains important for systems programming, embedded work, and understanding low-level fundamentals.",
        "learning_path": "C Basics → Pointers → Memory → Data Structures → Projects",
        "estimated_time": "1.5 Weeks",
        "priority": "Medium",
    },
    "C++": {
        "reason": "C++ is valuable for performance-critical applications, game engines, and systems programming.",
        "learning_path": "C++ Basics → OOP → STL → Templates → Advanced Projects",
        "estimated_time": "2 Weeks",
        "priority": "Medium",
    },
    "JavaScript": {
        "reason": "JavaScript powers web interfaces and is essential for modern frontend and full-stack development.",
        "learning_path": "JavaScript Basics → DOM → Async → ES6+ → Frameworks",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "TypeScript": {
        "reason": "TypeScript improves maintainability and safety for large-scale web applications.",
        "learning_path": "TypeScript Basics → Types → Interfaces → Advanced Types → Projects",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "HTML": {
        "reason": "HTML is the foundation of web content structure and accessibility.",
        "learning_path": "HTML Basics → Semantic Elements → Forms → Accessibility",
        "estimated_time": "3 Days",
        "priority": "High",
    },
    "CSS": {
        "reason": "CSS is required for creating responsive and polished user interfaces.",
        "learning_path": "CSS Basics → Layout → Flexbox → Grid → Responsive Design",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "Bootstrap": {
        "reason": "Bootstrap speeds up responsive UI development with reusable components.",
        "learning_path": "Bootstrap Basics → Grid → Components → Customization",
        "estimated_time": "3 Days",
        "priority": "Medium",
    },
    "Tailwind CSS": {
        "reason": "Tailwind CSS helps build modern, utility-first interfaces quickly.",
        "learning_path": "Tailwind Basics → Utility Classes → Configuration → Components",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "React": {
        "reason": "React is one of the most popular UI libraries for building interactive web applications.",
        "learning_path": "React Basics → Components → State → Hooks → Routing",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Angular": {
        "reason": "Angular is widely adopted for enterprise-grade single-page applications.",
        "learning_path": "Angular Basics → Components → Services → Routing → RxJS",
        "estimated_time": "1.5 Weeks",
        "priority": "Medium",
    },
    "Vue.js": {
        "reason": "Vue.js is a progressive framework used for lightweight and scalable frontend apps.",
        "learning_path": "Vue Basics → Components → State → Routing → Projects",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "Django": {
        "reason": "Django accelerates backend development with built-in admin, ORM, and security features.",
        "learning_path": "Django Basics → Models → Views → Templates → REST Framework",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Flask": {
        "reason": "Flask is a lightweight Python web framework used for APIs and microservices.",
        "learning_path": "Flask Basics → Routes → Templates → APIs → Deployment",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "FastAPI": {
        "reason": "FastAPI is popular for modern, high-performance Python APIs.",
        "learning_path": "FastAPI Basics → Pydantic → Routers → Authentication → Deploy",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "Node.js": {
        "reason": "Node.js is essential for JavaScript-based server-side development and tooling.",
        "learning_path": "Node.js Basics → Modules → Async → APIs → Deployment",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Express.js": {
        "reason": "Express.js is a minimal web framework commonly used with Node.js.",
        "learning_path": "Express Basics → Routing → Middleware → APIs → Authentication",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "SQL": {
        "reason": "SQL is essential for querying and managing relational data.",
        "learning_path": "SQL Basics → Joins → Aggregations → Indexes → Practice",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "MySQL": {
        "reason": "MySQL is a widely used relational database for web and business applications.",
        "learning_path": "MySQL Basics → Schemas → Queries → Joins → Optimization",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "PostgreSQL": {
        "reason": "PostgreSQL is a robust relational database used in modern application stacks.",
        "learning_path": "PostgreSQL Basics → Queries → Indexes → Constraints → Advanced SQL",
        "estimated_time": "5 Days",
        "priority": "High",
    },
    "MongoDB": {
        "reason": "MongoDB is commonly used for flexible document-based data storage.",
        "learning_path": "MongoDB Basics → Documents → Queries → Indexes → Aggregation",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "SQLite": {
        "reason": "SQLite is a lightweight embedded database useful for local apps and prototypes.",
        "learning_path": "SQLite Basics → Schema → Queries → Transactions → Practice",
        "estimated_time": "3 Days",
        "priority": "Low",
    },
    "Artificial Intelligence": {
        "reason": "Artificial Intelligence is a foundational area for modern automation and intelligent systems.",
        "learning_path": "AI Basics → Problem Solving → Search → Logic → Projects",
        "estimated_time": "2 Weeks",
        "priority": "High",
    },
    "Machine Learning": {
        "reason": "Machine Learning is central to predictive modeling and data-driven applications.",
        "learning_path": "ML Basics → Supervised Learning → Evaluation → Projects",
        "estimated_time": "2 Weeks",
        "priority": "High",
    },
    "Deep Learning": {
        "reason": "Deep Learning powers modern computer vision, NLP, and speech systems.",
        "learning_path": "Neural Networks → PyTorch/TensorFlow → Training → Projects",
        "estimated_time": "3 Weeks",
        "priority": "High",
    },
    "TensorFlow": {
        "reason": "TensorFlow is a leading framework for building and training machine learning models.",
        "learning_path": "TensorFlow Basics → Tensors → Models → Training → Deployment",
        "estimated_time": "10 Days",
        "priority": "High",
    },
    "Keras": {
        "reason": "Keras simplifies deep learning model building with a beginner-friendly API.",
        "learning_path": "Keras Basics → Layers → Models → Training → Projects",
        "estimated_time": "5 Days",
        "priority": "Medium",
    },
    "PyTorch": {
        "reason": "PyTorch is a popular deep learning framework used in research and production.",
        "learning_path": "PyTorch Basics → Tensors → Autograd → Training → Projects",
        "estimated_time": "10 Days",
        "priority": "High",
    },
    "Scikit-learn": {
        "reason": "Scikit-learn provides practical tools for classical machine learning workflows.",
        "learning_path": "Scikit-learn Basics → Preprocessing → Models → Evaluation",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "OpenCV": {
        "reason": "OpenCV is widely used for computer vision and image processing tasks.",
        "learning_path": "OpenCV Basics → Image Processing → Feature Detection → Projects",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "NumPy": {
        "reason": "NumPy is the foundation for numerical computing in Python.",
        "learning_path": "NumPy Basics → Arrays → Broadcasting → Linear Algebra",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "Pandas": {
        "reason": "Pandas is essential for data analysis and tabular data workflows.",
        "learning_path": "Pandas Basics → DataFrames → Cleaning → Analysis",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "Matplotlib": {
        "reason": "Matplotlib is used for creating charts and data visualizations.",
        "learning_path": "Matplotlib Basics → Charts → Styling → Visualization Projects",
        "estimated_time": "3 Days",
        "priority": "Medium",
    },
    "AWS": {
        "reason": "AWS is a major cloud platform for deployment, storage, and infrastructure services.",
        "learning_path": "AWS Basics → EC2/S3 → IAM → Deployment → Projects",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Azure": {
        "reason": "Azure is widely used for cloud hosting and enterprise application services.",
        "learning_path": "Azure Basics → Services → Deployment → Security → Projects",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "Google Cloud": {
        "reason": "Google Cloud offers modern infrastructure and AI services used by many teams.",
        "learning_path": "Google Cloud Basics → Compute → Storage → Deployment",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "Docker": {
        "reason": "Containerization is widely used for application deployment and DevOps workflows.",
        "learning_path": "Docker Basics → Images → Containers → Volumes → Docker Compose",
        "estimated_time": "5 Days",
        "priority": "High",
    },
    "Kubernetes": {
        "reason": "Kubernetes is a core platform for orchestrating containerized applications at scale.",
        "learning_path": "Kubernetes Basics → Pods → Services → Deployments → Helm",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Git": {
        "reason": "Git is essential for version control and collaborative software development.",
        "learning_path": "Git Basics → Commits → Branching → Merging → Collaboration",
        "estimated_time": "3 Days",
        "priority": "High",
    },
    "GitHub": {
        "reason": "GitHub is the standard platform for hosting repositories and managing collaboration workflows.",
        "learning_path": "GitHub Basics → Repositories → Pull Requests → Actions",
        "estimated_time": "3 Days",
        "priority": "High",
    },
    "GitHub Actions": {
        "reason": "GitHub Actions automates testing and deployment for modern software projects.",
        "learning_path": "Actions Basics → Workflows → CI/CD → Deployment",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "CI/CD": {
        "reason": "CI/CD practices speed up delivery and improve software reliability.",
        "learning_path": "CI/CD Basics → Pipelines → Testing → Deployment",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "REST API": {
        "reason": "REST APIs are widely used to connect frontend, backend, and third-party services.",
        "learning_path": "HTTP Basics → Endpoints → Requests → Authentication → Testing",
        "estimated_time": "4 Days",
        "priority": "High",
    },
    "GraphQL": {
        "reason": "GraphQL is useful for efficient, flexible API design in modern applications.",
        "learning_path": "GraphQL Basics → Queries → Mutations → Schemas → Tools",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "Flutter": {
        "reason": "Flutter is a popular framework for building cross-platform mobile applications.",
        "learning_path": "Flutter Basics → Widgets → State → Navigation → Apps",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "Android": {
        "reason": "Android development is important for building mobile apps for the largest mobile platform.",
        "learning_path": "Android Basics → Kotlin → UI → Lifecycle → Projects",
        "estimated_time": "1.5 Weeks",
        "priority": "Medium",
    },
    "Kotlin": {
        "reason": "Kotlin is the preferred language for modern Android development.",
        "learning_path": "Kotlin Basics → Syntax → Coroutines → Android Apps",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "React Native": {
        "reason": "React Native enables cross-platform mobile apps using React concepts.",
        "learning_path": "React Native Basics → Components → Navigation → APIs → Apps",
        "estimated_time": "1 Week",
        "priority": "Medium",
    },
    "Linux": {
        "reason": "Linux knowledge is valuable for servers, development environments, and DevOps work.",
        "learning_path": "Linux Basics → Shell → Filesystem → Permissions → Scripting",
        "estimated_time": "4 Days",
        "priority": "Medium",
    },
    "Data Science": {
        "reason": "Data Science combines statistics, analysis, and engineering for insight-driven solutions.",
        "learning_path": "Statistics → Python → Data Analysis → Visualization → Projects",
        "estimated_time": "2 Weeks",
        "priority": "High",
    },
    "Computer Vision": {
        "reason": "Computer Vision is essential for image and video understanding systems.",
        "learning_path": "CV Basics → OpenCV → Models → Projects",
        "estimated_time": "1.5 Weeks",
        "priority": "Medium",
    },
    "NLP": {
        "reason": "NLP powers language understanding and text-based AI applications.",
        "learning_path": "NLP Basics → Text Processing → Models → Projects",
        "estimated_time": "1.5 Weeks",
        "priority": "Medium",
    },
    "Generative AI": {
        "reason": "Generative AI is increasingly used to build copilots, assistants, and content tools.",
        "learning_path": "GenAI Basics → LLMs → Prompting → Fine-tuning → Projects",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "LLM": {
        "reason": "LLMs are central to modern AI applications and automation workflows.",
        "learning_path": "LLM Basics → Prompt Engineering → APIs → Evaluation",
        "estimated_time": "1 Week",
        "priority": "High",
    },
    "Prompt Engineering": {
        "reason": "Prompt engineering improves the reliability and quality of LLM outputs.",
        "learning_path": "Prompt Basics → Patterns → Evaluation → Iteration",
        "estimated_time": "3 Days",
        "priority": "Medium",
    },
}
